services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      - MYSQL_DATABASE=dbCountries
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - '3308:3306'
    volumes:
      - ./mysql/init_db:/docker-entrypoint-initdb.d
    networks:
      - my_network

  mysql-api-container:
    image: mysql_api:1.0
    container_name: mysql-api-container
    restart: always
    build: ./mysql_api
    ports:
      - '8000:8000'
    # environment:
    #   - MYSQL_HOST=mysql-container
    #   - MYSQL_PORT=3306
    #   - MYSQL_USER=root
    #   - MYSQL_PASSWORD=123
    networks:
      - my_network
      
  python-app-container:
    image: python-app:2.0
    container_name: python-app-container
    restart: always
    build: ./call_api
    ports:
      - '5000:5000'
    networks:
      - my_network
    depends_on:
      - mysql-api-container

  node_app-container:
    image: node:16-alpine
    build: ./view
    container_name: node_app-container
    ports:
      - "3000:3000"
    volumes:
      - .:/view
    environment:
      - NODE_ENV=development
    
networks:
  my_network:
    driver: bridge